// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4tQtxVFDqAvzh6sRQJuG5Kqfl3MDJ10c',
    appId: '1:158528976668:web:17f9ca9e5575a9855c6cd9',
    messagingSenderId: '158528976668',
    projectId: 'i-want-to-306f7',
    authDomain: 'i-want-to-306f7.firebaseapp.com',
    storageBucket: 'i-want-to-306f7.appspot.com',
    measurementId: 'G-0Q962B65F6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu2Tsb7VLTVooznJtcHL3L0eMUuTInDhk',
    appId: '1:158528976668:android:44b7c03792281b205c6cd9',
    messagingSenderId: '158528976668',
    projectId: 'i-want-to-306f7',
    storageBucket: 'i-want-to-306f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDID4tLlZsl6lAaJ50L6CBb76oFRfohrtk',
    appId: '1:158528976668:ios:8ffb606bdb89c6605c6cd9',
    messagingSenderId: '158528976668',
    projectId: 'i-want-to-306f7',
    storageBucket: 'i-want-to-306f7.appspot.com',
    iosClientId: '158528976668-ukd7qeh6pejtc9vi07ri4hof940pumub.apps.googleusercontent.com',
    iosBundleId: 'com.rishusharma.iWantTo',
  );
}
